### ISSUE TITLE
Map features colouring by date and user

### ISSUE THREAD

**Issue by willemarcel** [hotosm/OpenMapKitServer#40]
We have added the map visualization option on https://github.com/hotosm/OpenMapKitServer/pull/36, which includes a new geojson endpoint.

We are planning to add the possibility of change the items colours according to the submission date and user.

I noticed that the OSM file, and consequently the geojson file, doesn't have submission metadata (date and user), it only has the geoespatial data added on the submissions. So we need to decide if it's better to visualize the submission date (when the form was submitted) and username/device-id or if we should use the features date (when the feature was modified created on field) and user information .

If we decide to use the submission metadata, I could modify the geojson endpoint to include those informations as a field of the feature. I believe it wouldn't be much complex.

**Comment by danbjoseph** [comment]
Segregation of the vanilla ODK portions of the data from the OMK/OSM data was important as private data might be collected about a location (for example, nutrition information about a household) alongside OSM appropriate data (for example, roof type or street address). I'd still like to see a tool that merges data from the main part of survey with tags added to OSM features surveyed/created during an OpenMapKit type question and exports as geojson. For viewing/analysis privately in a GIS software and **not** for adding back into OSM. But I think that is a separate issue from metadata. Currently, I can't think of a reason why a user would want the submission metadata excluded from the geojson endpoint. And so I have no problem including the submission metadata in the geojson endpoint.

Somewhat related questions:
- How does the geojson endpoint handle a single submission with multiple OSM features? For example, a building polygon and POIs all added with one survey submission.
- Should there be a way to handle instances when a submission from a survey in which an ODK geo type question (`geopoint`, `geotrace`, `geoshape`) may have been collected with or instead of an OMK/OSM feature?

**Comment by smit1678** [comment]
> Currently, I can't think of a reason why a user would want the submission metadata excluded from the geojson endpoint. And so I have no problem including the submission metadata in the geojson endpoint.

I agree @danbjoseph 

> Should there be a way to handle instances when a submission from a survey in which an ODK geo type question (geopoint, geotrace, geoshape) may have been collected with or instead of an OMK/OSM feature?

That's a good question. @willemarcel I think we're only handling the OSM/OMK submission within the map and haven't fully integrated an ODK only submission (that includes geo information), right?

**Comment by willemarcel** [comment]
> That's a good question. @willemarcel I think we're only handling the OSM/OMK submission within the map and haven't fully integrated an ODK only submission (that includes geo information), right?

I don't know the details about ODK submissions... The geojson has the same data included in the osm files, what I did was just to convert the OSM file to geojson.
