### ISSUE TITLE
Choose a new CSS Framework

### ISSUE THREAD

**Issue by willemarcel** [hotosm/OpenMapKitServer#6]
I think Material Design Lite is a bit complicated and give less possibilities than other CSS Frameworks. We should choose a new CSS framework

My preferences:
* [Assembly](https://www.mapbox.com/assembly/) -> I like it because it's made for map projects and have a lot classes for margins, paddings, colours, backgrounds... it allows us to design writing the minimum quantity of CSS classes.
* [Bootstrap](http://getbootstrap.com/)

**Comment by bgirardot** [comment]
Would be good to keep an eye on other HOT tools. Using a common set of frameworks as much as  possible is good and helps leverage knowledge and experience.

The TM3 uses bootstrap I am pretty sure

**Comment by smit1678** [comment]
👍 Agreed that using frameworks that are familiar, easy, and well maintained. I'm not sure if we should pick single framework for all of HOT tools but choosing a framework and libraries that fit should be top priority. Sometimes there is a really good reason for deviating from a standard one.

Also since OMK is being maintained by the POSM project, will be curious of their input here since we'll be looking to contribute these changes back upstream. 

> The TM3 uses bootstrap I am pretty sure

yeah TM3 looks like it uses a mix of [Jeet](http://jeet.gs/) and [Bourbon](https://www.bourbon.io/), and Bootstrap.

**Comment by mojodna** [comment]
The POSM admin UI (and HOT Export Tool, though they're not really connected) uses Bootstrap (via [react-bootstrap](https://react-bootstrap.github.io/)) and [Blueprint JS](http://blueprintjs.com/) to augment it (since it's Bootstrap-based and includes lots of nice, additional components for more complex UIs).

**Comment by mojodna** [comment]
(Blueprint's table component, in particular, looks like it would be useful here.)

**Comment by willemarcel** [comment]
Thanks @mojodna ! So my opinion is to use bootstrap + blueprint, as it is used on several projects.

**Comment by willemarcel** [comment]
We choose bootstrap + blueprintjs
