### ISSUE TITLE
Add deployment upload  form page

### ISSUE THREAD

**Issue by willemarcel** [hotosm/OpenMapKitServer#74]
Also think about a page to admin the deployment files, allowing an admin user to delete the unneeded files.

**Comment by willemarcel** [comment]
**Proposal:**

* A page listing the deployment directories, allowing the admin users to navigate through them, create and delete folders. A form inside each subdirectory would allow to upload files to it.

**Comment by danbjoseph** [comment]
This is for the OSM bundles? Or for survey forms? What are the contents of the folders? What is a user uploading to a deployment? Or is the uploading only to create new deployments? The intention of this feature is just to provide the ability to remove old stuff? Do they need to be be able to create/upload with this level of detail/control?

**Comment by smit1678** [comment]
This is for the deployments on the OMK Android app. Our use case is more of a OMK-only use case, and not for POSM. We have been running OMK Server by itself and this increases the need for OMK Server to directly manage the mbtiles and OSM files available for OMK Androids clients to download for offline use. 

An survey manager or admin user will be uploading two files most likely -- mbtiles of satellite imagery, and then OSM files (1 or many). 

> Do they need to be be able to create/upload with this level of detail/control?

Yeah we've seen survey managers or admins need this level of detail when using OMK Server on the cloud. Instead of using a local POSM box which you can transfer mbtiles and OSM files to, this gives survey managers the ability manage the files that each OMK Android app can access.

**Comment by danbjoseph** [comment]
oh interesting. cool. what we first handled just with direct file transfer. makes sense.
how does the android client download things? through the OMK interface?

is the creation of folders just a top level thing or would it allow creation of a deeper level of organization?

**Comment by danbjoseph** [comment]
@dalekunce this issue is dealing with a standalone OMK deployment (no POSM) and uploading just the  osm and mbtiles files.

**Comment by willemarcel** [comment]
**Proposal:** a form that would allow to upload multiples file once and a name field that would define the name of the folder where the files will be saved.

**Comment by smit1678** [comment]
> Proposal: a form that would allow to upload multiples file once and a name field that would define the name of the folder where the files will be saved.

👍 I think this sounds good @willemarcel.

**Comment by willemarcel** [comment]
First part of the upload page... The user will select where to upload files to:

![screenshot_2019-01-21 openmapkit server](https://user-images.githubusercontent.com/666291/51482349-fd9f5400-1d74-11e9-82e8-3579acb9d94a.png)

**Comment by willemarcel** [comment]
It's done! https://github.com/hotosm/OpenMapKitServer/pull/86
